### ISSUE TITLE
Share Crosshair Code for this?

### ISSUE THREAD

**Issue by websecnl** [DrNseven/D3D12-Hook#3]
When i make a crosshair and i hide menu with 'insert' the crosshair disapears even through I am using GetBackgroundDrawList.

Any ideas?

```
    int m_width = ImGui::GetIO().DisplaySize.x;
    int m_height = ImGui::GetIO().DisplaySize.y;


    static bool Cross = false;
    static bool no_recoil = false;
    static bool no_spread = false;
    static bool no_sway = false;
    static bool no_bulletdrop = false;
    static bool show_res = false;
    static bool show_time = false;

    if (GetAsyncKeyState(VK_DELETE) & 1) // toggle crosshair with  delete key
        Cross = !Cross;

    if (ImGui::CollapsingHeader("Misc"))
    {
        if (ImGui::BeginTable("Options", 3))
        {
            ImGui::TableNextColumn(); ImGui::Checkbox("No Recoil", &no_recoil);
            ImGui::TableNextColumn(); ImGui::Checkbox("No Spread", &no_spread);
            ImGui::TableNextColumn(); ImGui::Checkbox("No Sway", &no_sway);
            ImGui::TableNextColumn(); ImGui::Checkbox("No Bulletdrop", &no_bulletdrop);
            ImGui::TableNextColumn(); ImGui::Checkbox("Show Resolution", &show_res);
            ImGui::TableNextColumn(); ImGui::Checkbox("Show Time", &show_time);
            ImGui::TableNextColumn(); ImGui::Checkbox("Crosshair", &Cross);
            if (Cross)
            {
                    ImGui::Begin("#crosshair", nullptr, ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoBackground | ImGuiWindowFlags_NoCollapse |
                        ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoSavedSettings | ImGuiWindowFlags_NoScrollbar);
                    ImGui::GetBackgroundDrawList()->AddCircle(ImVec2(m_width / 2, m_height / 2), 6, IM_COL32(255, 0, 0, 255), 100, 0.0f);
                    ImGui::End();
            }
            // ImGui::Render(); (Causes Crash)
            ImGui::EndTable();
        }
    }
    ```

**Comment by HeiDaShuai666** [comment]
Don't use 'if' yet, inject the DX12 demo. Mine shows the little red circle. I am curious which game you are playing?

int m_width = ImGui::GetIO().DisplaySize.x;
    int m_height = ImGui::GetIO().DisplaySize.y;
                    ImGui::Begin("#crosshair", nullptr, ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoBackground | ImGuiWindowFlags_NoCollapse |ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoSavedSettings | ImGuiWindowFlags_NoScrollbar);
                    ImGui::GetBackgroundDrawList()->AddCircle(ImVec2(m_width / 2, m_height / 2), 6, IM_COL32(255, 0, 0, 255), 100, 0.0f);
                    ImGui::End();

**Comment by websecnl** [comment]
> Don't use 'if' yet, inject the DX12 demo. Mine shows the little red circle. I am curious which game you are playing?
> 
> int m_width = ImGui::GetIO().DisplaySize.x; int m_height = ImGui::GetIO().DisplaySize.y; ImGui::Begin("#crosshair", nullptr, ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoBackground | ImGuiWindowFlags_NoCollapse |ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoSavedSettings | ImGuiWindowFlags_NoScrollbar); ImGui::GetBackgroundDrawList()->AddCircle(ImVec2(m_width / 2, m_height / 2), 6, IM_COL32(255, 0, 0, 255), 100, 0.0f); ImGui::End();

Halo Infinite,  not really playing.. just using this game to learn more about DX12 stuff as it has no Anti Cheat

btw which if are you referring to?

can you share your crosshair code, because i cant really seem to keep any of my changes... the moment i press Insert everything is disabled and gone (Draw doesnt remain on background)

**Comment by daztaw** [comment]
> > Don't use 'if' yet, inject the DX12 demo. Mine shows the little red circle. I am curious which game you are playing?
> > int m_width = ImGui::GetIO().DisplaySize.x; int m_height = ImGui::GetIO().DisplaySize.y; ImGui::Begin("#crosshair", nullptr, ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoBackground | ImGuiWindowFlags_NoCollapse |ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoSavedSettings | ImGuiWindowFlags_NoScrollbar); ImGui::GetBackgroundDrawList()->AddCircle(ImVec2(m_width / 2, m_height / 2), 6, IM_COL32(255, 0, 0, 255), 100, 0.0f); ImGui::End();
> 
> Halo Infinite, not really playing.. just using this game to learn more about DX12 stuff as it has no Anti Cheat
> 
> btw which if are you referring to?
> 
> can you share your crosshair code, because i cant really seem to keep any of my changes... the moment i press Insert everything is disabled and gone (Draw doesnt remain on background)

Here is the fix.

`if (ShowMenu == true) {
		

		if (ImGui::CollapsingHeader("Misc"))
		{
			if (ImGui::BeginTable("Options", 3))
			{
				ImGui::TableNextColumn(); ImGui::Checkbox("No Recoil", &no_recoil);
				ImGui::TableNextColumn(); ImGui::Checkbox("No Spread", &no_spread);
				ImGui::TableNextColumn(); ImGui::Checkbox("No Sway", &no_sway);
				ImGui::TableNextColumn(); ImGui::Checkbox("No Bulletdrop", &no_bulletdrop);
				ImGui::TableNextColumn(); ImGui::Checkbox("Show Resolution", &show_res);
				ImGui::TableNextColumn(); ImGui::Checkbox("Show Time", &show_time);
				ImGui::TableNextColumn(); ImGui::Checkbox("Crosshair", &Cross);
				
				// ImGui::Render(); (Causes Crash)
				ImGui::EndTable();
			}
			
		}

	}
	if (GetAsyncKeyState(VK_DELETE) & 1) // toggle crosshair with  delete key
		Cross = !Cross;
	if (Cross)
	{
		ImGui::Begin("#crosshair", nullptr, ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoBackground | ImGuiWindowFlags_NoCollapse |
			ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoSavedSettings | ImGuiWindowFlags_NoScrollbar);
		ImGui::GetBackgroundDrawList()->AddCircle(ImVec2(m_width / 2, m_height / 2), 6, IM_COL32(255, 0, 0, 255), 100, 0.0f);

	}
	ImGui::EndFrame();`

**Comment by websecnl** [comment]
Thank you
